name: my-blog

# базовый шаблон для образа
x-base-app: &base_app
  build: .
  env_file: .env
  volumes:
    - ./source:/app/source # только код backend
    - uploads_data:/app/uploads # сохраняем папку с локальным хранилищем
    - logs_data:/app/logs # папка с логами
  depends_on:
    - postgres
    - redis

services:

  # приложение
  my_app:
    <<: *base_app
    container_name: my-app-container
    ports:
      - "8000:8000"
    # запуск с перезагрузкой и отслеживанием за изменениями файлов
    command: uv run uvicorn source.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/source
    # новый вариант
    #command: uv run uvicorn source.main:app --host 0.0.0.0 --port 8000
    # старый вариант (в main запускался сервер)
    #command: uv run -m source.main --uvicorn_reload

  # celery для выполнения задач
  celery_worker:
    <<: *base_app
    container_name: celery-worker-container
    command: uv run celery -A source.celery_app.celery_app worker --loglevel=info

  # celery для периодичных задач
  celery_beat:
    <<: *base_app
    container_name: celery-beat-container
    command: uv run celery -A source.celery_app.celery_app beat --loglevel=info

  postgres:
    image: postgres:17-alpine
    container_name: postgres-container
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-container
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"

  # fronend
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev-contrainer
    env_file: ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  uploads_data:
  logs_data: