name: my-blog

# базовый шаблон для образа
x-base-app: &base_app
  build: .
  env_file: .env
  volumes:
    - ./source:/app/source # только код проекта
    - uploads_data:/app/uploads # отдельно папка для локального хранилища
  depends_on:
    - postgres
    - redis

services:

  # приложение
  my_app:
    <<: *base_app
    container_name: my-app-container
    ports:
      - "8000:8000"
    command: uv run -m source.main --uvicorn_reload

  # celery для выполнения задач
  celery_worker:
    <<: *base_app
    container_name: celery-worker-container
    command: uv run celery -A source.celery_app.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # celery для периодичных задач
  celery_beat:
    <<: *base_app
    container_name: celery-beat-container
    command: uv run celery -A source.celery_app.celery_app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  postgres:
    image: postgres:17
    container_name: postgres-container
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-container
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
  uploads_data: