name: my-test-blog

services:

  # приложение
  my_app_test:
    build: .
    env_file: .test.env
    container_name: my-test-app-container
    ports:
      - "8000:8000"
    volumes:
      - ./source:/app/source # код backend
      - ./tests:/app/tests # папка с тестами
      - ./pytest.ini:/app/pytest.ini # конфигурационный файл для тестов
    depends_on:
      postgres_test:
        condition: service_healthy
      redis_test:
        condition: service_started
    command: uv run pytest

  postgres_test:
    image: postgres:17-alpine
    container_name: testpg-container
    env_file: .test.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis_test:
    image: redis:7-alpine
    env_file: .test.env
    ports:
      - "${REDIS_PORT}:6379"
