"""your message

Revision ID: 14c0955be4fb
Revises: 4288b55d5dd8
Create Date: 2026-07-24 13:55:43.487384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14c0955be4fb'
down_revision: Union[str, Sequence[str], None] = '4288b55d5dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachment_medias_user_id_fkey'), 'attachment_medias', type_='foreignkey')
    op.create_foreign_key(None, 'attachment_medias', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'media_urls')
    op.drop_column('posts', 'media_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_urls', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('media_urls', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attachment_medias', type_='foreignkey')
    op.create_foreign_key(op.f('attachment_medias_user_id_fkey'), 'attachment_medias', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
