"""added import post_reaction_model to alembic file

Revision ID: 161394010c75
Revises: f754eddb679d
Create Date: 2026-06-20 12:20:44.023927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161394010c75'
down_revision: Union[str, Sequence[str], None] = 'f754eddb679d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_reactions', sa.Column('reaction_type', sa.Enum('LIKE', 'DISLIKE', 'FIRE', 'SHIT', 'LAUGH', name='typereaction', native_enum=False), nullable=False))
    op.drop_column('post_reactions', 'reation_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_reactions', sa.Column('reation_type', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_column('post_reactions', 'reaction_type')
    # ### end Alembic commands ###
