"""add views count to post

Revision ID: 42449f3a7bce
Revises: 9b85d16a64d2
Create Date: 2026-06-20 10:32:26.477744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42449f3a7bce'
down_revision: Union[str, Sequence[str], None] = '9b85d16a64d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views_count')
    # ### end Alembic commands ###
