"""change id type from int to uuid

Revision ID: 6a073d959f4c
Revises: 320355ecd9fb
Create Date: 2026-06-17 15:59:46.620247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a073d959f4c'
down_revision: Union[str, Sequence[str], None] = '320355ecd9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    # sa.Column('username', sa.String(length=20), nullable=False),
    # sa.Column('email', sa.String(), nullable=False),
    # sa.Column('password_hash', sa.String(length=255), nullable=False),
    # sa.Column('role', sa.Enum('ADMIN', 'USER', name='roleenum', native_enum=False), server_default='user', nullable=False),
    # sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    # sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # """Downgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_username'), table_name='users')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.drop_table('users')
    # # ### end Alembic commands ###
