"""add orig_name column to attachment_media

Revision ID: acc17ccd4078
Revises: 756043df0ee1
Create Date: 2026-08-13 08:32:16.093959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc17ccd4078'
down_revision: Union[str, Sequence[str], None] = '756043df0ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment_medias', sa.Column('orig_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment_medias', 'orig_name')
    # ### end Alembic commands ###
