"""create table attachment medias

Revision ID: d4f3fdcc2e84
Revises: 32796ea4b358
Create Date: 2026-07-06 12:26:14.522935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f3fdcc2e84'
down_revision: Union[str, Sequence[str], None] = '32796ea4b358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment_medias',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', name='filetypeenum', native_enum=False), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('is_temporary', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('size <= 10485760', name='ck_file_size'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_medias_comment_id'), 'attachment_medias', ['comment_id'], unique=False)
    op.create_index(op.f('ix_attachment_medias_post_id'), 'attachment_medias', ['post_id'], unique=False)
    op.create_index(op.f('ix_attachment_medias_user_id'), 'attachment_medias', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachment_medias_user_id'), table_name='attachment_medias')
    op.drop_index(op.f('ix_attachment_medias_post_id'), table_name='attachment_medias')
    op.drop_index(op.f('ix_attachment_medias_comment_id'), table_name='attachment_medias')
    op.drop_table('attachment_medias')
    # ### end Alembic commands ###
