"""changed reaction_type column in post_reaction

Revision ID: f754eddb679d
Revises: c41b53e97214
Create Date: 2026-06-20 12:08:14.093801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f754eddb679d'
down_revision: Union[str, Sequence[str], None] = 'c41b53e97214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_reactions', 'reation_type',
               existing_type=postgresql.ENUM('LIKE', 'DISLIKE', 'FIRE', 'SHIT', 'LAUGH', name='typereaction'),
               type_=sa.Enum('LIKE', 'DISLIKE', 'FIRE', 'SHIT', 'LAUGH', name='typereaction', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_reactions', 'reation_type',
               existing_type=sa.Enum('LIKE', 'DISLIKE', 'FIRE', 'SHIT', 'LAUGH', name='typereaction', native_enum=False),
               type_=postgresql.ENUM('LIKE', 'DISLIKE', 'FIRE', 'SHIT', 'LAUGH', name='typereaction'),
               existing_nullable=False)
    # ### end Alembic commands ###
