server {
    listen 80;
    server_name localhost;


    # Включаем Gzip сжатие
    gzip on;
    # Уровень сжатия от 1 до 9
    gzip_comp_level 6;
    # Минимальный размер файла в байтах, который стоит сжимать
    gzip_min_length 256;
    # Разрешаем сжатие для проксированных запросов (от бэкенда или Vite)
    gzip_proxied any;
    # Указываем типы файлов, которые нужно сжимать
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        image/svg+xml;


    # 1. ПРЯМАЯ раздача загруженных файлов через Nginx
    location /api/v1/app/uploads/ {

        # Используем alias и указываем точный путь к папке с файлами внутри контейнера Nginx
        alias /app/uploads/; 
        
        # Теперь при запросе /api/v1/app/uploads/filename.png
        # Nginx заменит префикс /api/v1/app/uploads/ на /app/uploads/
        # и будет искать файл по правильному пути: /app/uploads/filename.png
        
        # Полезные настройки для статики:
        expires 7d;                    # Кэшировать в браузере на 7 дней
        add_header Cache-Control "public, no-transform";
    }

    # 2. Проксирование документации FastAPI и OpenAPI схемы и админки
    location ~ ^/(docs|docs|redoc|openapi\.json|admin)(/|$) {
        proxy_pass http://my_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Проксирование API-запросов на FastAPI
    location /api/ {
        proxy_pass http://my_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Поддержка WebSocket для Vite Hot Module Reloading (HMR)
    # Vite использует этот путь для общения с браузером
    location /@vite/ {
        proxy_pass http://frontend-dev:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 4. Проксирование основного UI на Vite Dev Server
    # Сюда попадают запросы к /src/, /node_modules/, @fs и т.д.
    location / {
        proxy_pass http://frontend-dev:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}